# Generated by Django 5.1.3 on 2024-11-18 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_content_options_content_order_module_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='ownner',
            new_name='owner',
        ),
    ]
