# Generated by Django 5.1.3 on 2024-11-19 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_rename_ownner_course_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
